" In case if you made external file for configuration
" source ~/.vim/vimrc

" Functional part
set nocompatible " Tunring off vi compatibility features
set hidden " Turning on working with multiple files with switching
set wildmenu " Making command line completition kinda like in zsh
set showcmd " Showing partial commands in the last line of the screen
set nomodeline " Turning off modeline (theoreticly, for security protection)
set autoindent " When creating line, keep first simbol, like '#' or '//'
set nostartofline " Keep the same distance from left, as previous line, when creating new line
set confirm " Making dialogue about saving changes instead of fail
set mouse=a " Turning on wirking with mouse
set ttymouse=xterm2
let &titleold=getcwd() " Turn of 'Thanks for flying Vim' when exit
set lz " Lazy redraw of screen after script
set encoding=utf8 " Default encoding
set ttyfast " Fast connecton to terminal
" Working with search
set hlsearch " Highliting search results
set ignorecase " Case insensetive search
set smartcase " But if writing with CAPITAL letters, then search by it
set incsearch " Interactive searching - show as you type
" Interface settings
syntax on " Turning on syntax highlighting
set number " Show number of line
set laststatus=2 " Always show status bar
set title " Show terminal title
set scrolloff=7 " Show 3 lines around cursor
set linespace=4 " Let some additional lines to show
  " Turning of BEEPs for sure
set visualbell 
set noerrorbells
set t_vb=
set tm=500
  " List for substitutions
set listchars=tab:->,eol:¬ " Instead of Tab show ->
set list " Turning on list
" Keyboard builds
set backspace=indent,eol,start " Changing BACKSPACE work for more usability
  " Making fast movement in editor
inoremap jj <ESC>
nnoremap ; :
vnoremap ; :
" Work with indentation (space/tab)
set expandtab
set shiftwidth=4
set softtabstop=4
" Sptit screen in different parts
nnoremap <leader>g <C-w>v<C-w>l
nnoremap <leader>s <C-w>s<C-w>l
" Move with many windows
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-h> <C-w>h
nnoremap <C-l> <C-w>l
" REgular expression settings
set gdefault " Make 'g' setting default in lines
" Add russian mapping
map ё `
map й q
map ц w
map у e
map к r
map е t
map н y
map г u
map ш i
map щ o
map з p
map х [
map ъ ]
map ф a
map ы s
map в d
map а f
map п g
map р h
map о j
map л k
map д l
map ж ;
map э '
map я z
map ч x
map с c
map м v
map и b
map т n
map ь m
map б ,
map ю .
map Ё ~
map Й Q
map Ц W
map У E
map К R
map Е T
map Н Y
map Г U
map Ш I
map Щ O
map З P
map Х {
map Ъ }
map Ф A
map Ы S
map В D
map А F
map П G
map Р H
map О J
map Л K
map Д L
map Ж :
map Э "
map Я Z
map Ч X
map С C
map М V
map И B
map Т N
map Ь M
map Б <
map Ю >
